=== mdepalma1/tema3_marcas/Pack 4/4.1.miriamdepalma.dtd
<!ELEMENT fitxers (llistafactures+)>
<!ELEMENT llistafactures (factura+)>
<!ELEMENT factura (emisor, pagador, import)>
<!ELEMENT emisor (nom, volum-vendes?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT volum-vendes (#PCDATA)>
<!ELEMENT pagador (nom, volum-vendes?)>
<!ELEMENT import (#PCDATA)>
<!ATTLIST factura data CDATA #IMPLIED>
<!ATTLIST emisor cif CDATA #REQUIRED>

=== mdepalma1/tema3_marcas/Pack 4/4.1.miriamdepalma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fitxers SYSTEM "4.1.miriamdepalma.dtd">
<fitxers>
  <llistafactures>
    <factura data=" ">
      <emisor cif=" ">
        <nom></nom>
        <volum-vendes></volum-vendes>
      </emisor>
      <pagador>
        <nom></nom>
        <volum-vendes></volum-vendes>
      </pagador>
      <import></import>
    </factura>
  </llistafactures>
</fitxers>
