=== mdepalma1/tema3_marcas/Pack 4/4.2.miriamdepalma.dtd
<!ELEMENT llistacursos (cursos+)>
<!ELEMENT cursos (alumne+)>
<!ELEMENT alumne (dni, nom, cognom, segon-cognom?, llista-assignatures)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT segon-cognom (#PCDATA)>
<!ELEMENT llista-assignatures (assignatura+)>
<!ELEMENT assignatura (nom, professor)>
<!ELEMENT professor (NRP, nom, cognom, segon-cognom?)>
<!ELEMENT NRP (#PCDATA)>
<!ATTLIST assignatura codi CDATA #REQUIRED>

=== mdepalma1/tema3_marcas/Pack 4/4.2.miriamdepalma.xml
<?xlm version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistacursos SYSTEM "4.2.miriamdepalma.dtd">
<llistacursos>
  <cursos>
    <alumne>
      <dni></dni>
      <nom></nom>
      <cognom></cognom>
      <segon-cognom></segon-cognom>
      <llista-assignatures>
        <assignatura codi=" ">
          <nom></nom>
          <professor>
            <NRP></NRP>
            <nom></nom>
            <cognom></cognom>
            <segon-cognom></segon-cognom>
          </professor>
        </assignatura>
      </llista-assignatures>
    </alumne>
  </cursos>
</llistacursos>
