=== mdepalma1/tema3_marcas/Pack 4/4.4.miriamdepalma.dtd
<!ELEMENT llistat (futurs+, divises+, bons+, lletres+)>
<!ELEMENT futurs (mercat?)>
<!ELEMENT mercat (procedencia)>
<!ELEMENT procedencia (#PCDATA)>
<!ELEMENT divises (#PCDATA)>
<!ELEMENT bons (pais_procedencia)>
<!ELEMENT pais_procedencia (EMPTY)>
<!ELEMENT lletres (#PCDATA)>
<!ATTLIST futurs preu CDATA #REQUIRED>
<!ATTLIST futurs estable CDATA #IMPLIED>
<!ATTLIST bons preu CDATA #REQUIRED>
<!ATTLIST bons estable CDATA #IMPLIED>
<!ATTLIST lletres preu CDATA #REQUIRED>

=== mdepalma1/tema3_marcas/Pack 4/4.4.miriamdepalma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE llistat SYSTEM "4.4.miriamdepalma.dtd">
<llistat>
    <futurs preu=" ">
        <mercat>
            <procedencia></procedencia>
        </mercat>
    </futurs>
    <divises preu=" " estable=" "></divises>
    <bons preu=" " estable=" ">
        <pais_procedencia></pais_procedencia>
    </bons>
    <lletres preu=" "></lletres>
</llistat>
