=== mdepalma1/tema3_marcas/Pack 2/2.3.miriamdepalma.dtd
<!ELEMENT comanda (tractor+)>
<!ELEMENT tractor (components+)>
<!ELEMENT components (nom-fabricant, data-entrega, fragilidad, pes-unitat, nombre-de-serie, kmmaxims?)>
<!ELEMENT nom-fabricant (#PCDATA)>
<!ELEMENT data-entrega (dia?, mes, any)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT fragilidad (#PCDATA)>
<!ELEMENT pes-unitat (#PCDATA)>
<!ELEMENT nombre-de-serie (#PCDATA)>
<!ELEMENT kmmaxims (#PCDATA)>

<!ATTLIST nom-fabricant nom-del-fabricant CDATA #REQUIRED>
<!ATTLIST mes mes-entrega CDATA #REQUIRED>
<!ATTLIST any any-entrega CDATA #REQUIRED>
<!ATTLIST fragilidad fragil CDATA #IMPLIED>
<!ATTLIST pes-unitat unitat CDATA #REQUIRED>

=== mdepalma1/tema3_marcas/Pack 2/2.3.MiriamdePalma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "2.3.miriamdepalma.dtd">

<comanda>
  <tractor>
    <components>
      <nom-fabricant nom-del-fabricant=" "></nom-fabricant>
      <data-entrega>
        <dia></dia>
        <mes mes-entrega=" "></mes>
        <any any-entrega=" "></any>
      </data-entrega>
      <fragilidad fragil= " "></fragilidad>
      <pes-unitat unitat="quilos"></pes-unitat>
      <nombre-de-serie></nombre-de-serie>
      <kmmaxims></kmmaxims>
    </components>
  </tractor>
</comanda>
