=== mdepalma1/tema3_marcas/Pack 3/3.3.miriamdepalma.dtd
<!ELEMENT entrega (lot+)>
<!ELEMENT lot (palet+)>
<!ELEMENT palet (nombre-caixes, contingut, pes, forma-manipulacio)>
<!ELEMENT nombre-caixes (#PCDATA)>
<!ELEMENT pes (#PCDATA)>
<!ELEMENT forma-manipulacio (#PCDATA)>
<!ELEMENT contingut (nom-component, procedencia*, num-serie, pes-component, unitat-de-pes?)>
<!ELEMENT nom-component (#PCDATA)>
<!ELEMENT procedencia (#PCDATA)>
<!ELEMENT num-serie (#PCDATA)>
<!ELEMENT pes-component (#PCDATA)>
<!ELEMENT unitat-de-pes (#PCDATA)>

=== mdepalma1/tema3_marcas/Pack 3/3.3.miriamdepalma.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entrega SYSTEM "3.3.miriamdepalma.dtd">
<entrega>
    <lot>
        <palet>
            <nombre-caixes></nombre-caixes>
            <contingut>
                <nom-component></nom-component>
                <procedencia></procedencia>
                <num-serie></num-serie>
                <pes-component></pes-component>
                <unitat-de-pes></unitat-de-pes>
            </contingut>
            <pes></pes>
            <forma-manipulacio></forma-manipulacio>
        </palet>
    </lot>
</entrega>
